# Site settings
title: HONGBO ZHA
description: personal website of hongbo zha
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Platform Researcher
user_description: I optimize UI functions and AI algorithms for famous apps, e.g., TikTok.
user_description2: I am pleased to communicate with professionals and academia.
user_description3: I can give support on your exciting research projects.
user_title: Hongbo Zha, PM, ex-BA
email: hongbo_zha@outlook.com
twitter_username:
phone_username: 008615162140513
facebook_username:
linkedin_username:
github_username: hongbozha
instagram_username:
wechat_username: fymhj951007
medium_username:
medium_url:
gplus_username:

exclude: ['package.json', 'node_modules', 'vendor']
