# Site settings
title: HONGBO ZHA
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: EXPERIENCE DEVELOPER
user_description: I'm a Product Manager and a Strategy Consultant in the Social Media Industry. I optimize UI functions and AI recommendation algorithms for famous apps, e.g., TikTok.
user_description2: Lately, I have been interested in the below topics. I am pleased to communicate my info and insights with professionals. I am also glad to talk with academia to collaborate.
user_description3: If you'd like to invite me to collaborate on exciting projects, it will be my pleasure, and I can give support on the below skills.
user_title: Hongbo Zha
email: hongbo_zha@outlook.com
# twitter_username: lorem_ipsum
phone_username: 008615162140513
facebook_username:
linkedin_username:
github_username: hongbozha
instagram_username:
wechat_username: fymhj951007
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

