# Site settings
title: HONGBO ZHA
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Develop the Greatest App
user_description: I'm a Product Manager and a Strategy Consultant in the Social Media Industry. I optimize UI functions and AI recommendation algorithms for famous apps, e.g., TikTok. Lately, I have been interested in content ecosystems and AIGC.
user_title: Hongbo Zha
email: hongbo_zha@outlook.com
# twitter_username: lorem_ipsum
instagram_username:
facebook_username:
linkedin_username:
github_username:
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

